"""fix models

Revision ID: 6c0d7fb2a6a8
Revises: d39c8fe66a72
Create Date: 2025-03-31 11:16:53.753827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0d7fb2a6a8'
down_revision: Union[str, None] = 'd39c8fe66a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_speciality_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'speciality_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('speciality_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_speciality_id_fkey', 'orders', 'specialities', ['speciality_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
