"""add enum to net model

Revision ID: d39c8fe66a72
Revises: d5873b09a2bc
Create Date: 2025-03-31 10:40:22.936300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39c8fe66a72'
down_revision: Union[str, None] = 'd5873b09a2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nets', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RIBBON', 'BOW', name='nettype'),
               existing_nullable=False)
    op.alter_column('nets', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PLANNED', 'WORKING', 'CONFIRMATION', 'COMPLETED', 'CANCELED', name='netstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nets', 'status',
               existing_type=sa.Enum('PLANNED', 'WORKING', 'CONFIRMATION', 'COMPLETED', 'CANCELED', name='netstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('nets', 'type',
               existing_type=sa.Enum('RIBBON', 'BOW', name='nettype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
